version: "2"
services:

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - monitoring
    volumes:
      - grafana-volume:/var/lib/grafana

  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    networks:
      - monitoring
    volumes:
      - influxdb-volume:/var/lib/influxdb

  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    networks:
      - monitoring
    volumes:
      - $PWD/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /proc:/host/proc:ro

networks:
  monitoring:

volumes:
  grafana-volume:
    external: true
  influxdb-volume:
    external: true
